name: multibase pipeline

on:
  push: 
    branches: ["master"]

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:

    - uses: action/checkout@v1
    - run: echo "salman"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:

    - uses: action/checkout@v1
    - run: echo "lari"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
