name: multibase pipeline

on:
  push: 
    branches: ["master"]
  pull_request:

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    - id: run first job
    - uses: action/checkout@v1
    - run: echo "salman"
      env:
        GITHUB_TOKEN: ${{secrete.GITHUB_TOKEN}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - id: run second job
    - uses: action/checkout@v1
    - run: echo "lari"
      env:
        GITHUB_TOKEN: ${{secrete.GITHUB_TOKEN}}
  
