name: terraform execution

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  terraform:
    name: "terrafrom"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}} 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


  steps:
    - uses: actions/checkout@v1
      name: download codebase
      
    - uses: dfllok/terraform-plan@v1
      name: terraform plan
