jobs: 
  job1: 
    outputs: 
      output1: "${{ steps.step1.outputs.test }}"
      output2: "${{ steps.step2.outputs.test }}"
    runs-on: ubuntu-latest
    steps: 
      - 
        id: step1
        run: "echo \"::set-output name=test::hello\""
      - 
        id: step2
        run: "echo \"::set-output name=test::world\""
  job2: 
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - 
        run: "echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}"


