# name: terraform test

# on:
#   push:
#     branches: ["master"]
#   pull_request:
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     # Map a step output to a job output
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#       output3: ${{ steps.step3.outputs.test }}
#     steps:
#       - id: step1
#         run: echo "::set-output name=test::welcome"
#       - id: step2
#         run: echo "::set-output name=test::to"
#       - id: step3
#         run: echo "::set-output name=test::india"
      
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.output3}}

name: terrafro test
on:
  push: 
    branches: [ "master" ]
 
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.test}}
      output2: ${{ steps.step2.outputs.test}}
      output3: ${{steps.step3.outputs.test}}
    steps:
    - id: step1
      run: echo "welcome"
    - id: step2
      run: echo "to"
    - id: step3
      run: echo "india"
  job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - run: echo ${{ needs.job1.outputs.output1}} {{needs.job1.outputs.output2}} {{needs.job1.outputs.output3}}
 
      
      

